version: "3.9"

services:
  backend:
    build: ./backend
    container_name: plant-disease-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/model:/app/model
    environment:
      - MODEL_PATH=/app/model/plant_disease_model.keras
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: plant-disease-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
