"""
Disease Database
Maps all 38 PlantVillage classes to structured treatment information.
"""

DISEASE_DB = {
    "Apple___Apple_scab": {
        "crop": "Apple",
        "disease": "Apple Scab",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Apple scab is a fungal disease caused by Venturia inaequalis. It produces olive-green or brown lesions on leaves, fruit, and twigs.",
        "symptoms": [
            "Olive-green to brown spots on leaves",
            "Velvety texture on lesions",
            "Premature leaf drop",
            "Scabby, cracked lesions on fruit",
        ],
        "treatment": [
            "Apply fungicides containing captan or myclobutanil",
            "Spray at 10-14 day intervals during wet periods",
            "Remove and destroy fallen leaves",
            "Prune to improve air circulation",
        ],
        "prevention": [
            "Plant scab-resistant apple varieties",
            "Apply dormant copper sprays before bud break",
            "Rake and remove fallen leaves in autumn",
            "Avoid overhead irrigation",
        ],
    },
    "Apple___Black_rot": {
        "crop": "Apple",
        "disease": "Black Rot",
        "is_healthy": False,
        "severity": "High",
        "description": "Black rot is caused by the fungus Botryosphaeria obtusa. It affects fruit, leaves, and bark, causing significant losses.",
        "symptoms": [
            "Purple spots on leaves that enlarge with yellow halos",
            "Fruit begins as small red spots, turns brown then black",
            "Mummified fruit remaining on tree",
            "Cankers on branches",
        ],
        "treatment": [
            "Apply captan or thiophanate-methyl fungicides",
            "Remove mummified fruit and dead wood immediately",
            "Prune out infected branches with 6 inch margin",
            "Dispose of pruned material away from orchard",
        ],
        "prevention": [
            "Maintain tree vigor through proper nutrition",
            "Prune annually to remove dead wood",
            "Control fire blight and other wounds",
            "Apply protective fungicides from pink stage through harvest",
        ],
    },
    "Apple___Cedar_apple_rust": {
        "crop": "Apple",
        "disease": "Cedar Apple Rust",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Caused by Gymnosporangium juniperi-virginianae, this fungal disease requires both apple and cedar/juniper trees to complete its lifecycle.",
        "symptoms": [
            "Bright orange-yellow spots on upper leaf surface",
            "Tube-like structures on underside of leaves",
            "Premature defoliation in severe cases",
            "Orange spots on fruit",
        ],
        "treatment": [
            "Apply myclobutanil or propiconazole fungicides",
            "Begin sprays at pink stage and repeat every 7-10 days",
            "Remove nearby cedar trees if feasible",
        ],
        "prevention": [
            "Plant rust-resistant apple varieties",
            "Remove galls from cedar trees in winter",
            "Apply preventive fungicide sprays in spring",
        ],
    },
    "Apple___healthy": {
        "crop": "Apple",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The apple plant appears healthy with no visible signs of disease.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Continue regular monitoring",
            "Maintain proper irrigation and nutrition",
            "Apply preventive fungicide sprays as scheduled",
        ],
    },
    "Blueberry___healthy": {
        "crop": "Blueberry",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The blueberry plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular monitoring", "Maintain soil pH between 4.5-5.5"],
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "crop": "Cherry",
        "disease": "Powdery Mildew",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Powdery mildew on cherry is caused by Podosphaera clandestina, producing white powdery growth on leaves and shoots.",
        "symptoms": [
            "White powdery coating on young leaves",
            "Curled and distorted leaves",
            "Stunted shoot growth",
            "Reduced fruit quality",
        ],
        "treatment": [
            "Apply sulfur-based fungicides",
            "Use potassium bicarbonate sprays",
            "Apply neem oil as organic alternative",
            "Prune heavily infected shoots",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Ensure good air circulation through pruning",
            "Avoid excessive nitrogen fertilization",
            "Apply preventive sulfur sprays",
        ],
    },
    "Cherry_(including_sour)___healthy": {
        "crop": "Cherry",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The cherry plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular monitoring", "Annual pruning for air circulation"],
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "crop": "Corn (Maize)",
        "disease": "Gray Leaf Spot",
        "is_healthy": False,
        "severity": "High",
        "description": "Gray leaf spot, caused by Cercospora zeae-maydis, is one of the most significant corn diseases worldwide.",
        "symptoms": [
            "Rectangular, gray-to-tan lesions parallel to leaf veins",
            "Lesions may coalesce causing large blighted areas",
            "Lower leaves affected first, progressing upward",
            "Premature plant death in severe cases",
        ],
        "treatment": [
            "Apply strobilurin or triazole fungicides at tasseling",
            "Use products containing azoxystrobin or propiconazole",
            "Apply when 50% of plants show disease below ear leaf",
        ],
        "prevention": [
            "Plant resistant hybrids",
            "Practice crop rotation with non-host crops",
            "Tillage to reduce infected residue",
            "Avoid planting in high-risk fields two years in a row",
        ],
    },
    "Corn_(maize)___Common_rust_": {
        "crop": "Corn (Maize)",
        "disease": "Common Rust",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Common rust is caused by Puccinia sorghi and appears as brick-red to brown pustules on both leaf surfaces.",
        "symptoms": [
            "Small, circular to elongated brick-red pustules on leaves",
            "Pustules present on both leaf surfaces",
            "Leaves turn yellow and die in severe infections",
            "Reduced photosynthesis and yield",
        ],
        "treatment": [
            "Apply triazole fungicides (propiconazole, tebuconazole)",
            "Treat when rust is detected before tasseling",
            "Strobilurin fungicides also effective",
        ],
        "prevention": [
            "Plant rust-resistant corn hybrids",
            "Early planting to escape peak rust periods",
            "Monitor fields regularly during summer",
        ],
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "crop": "Corn (Maize)",
        "disease": "Northern Leaf Blight",
        "is_healthy": False,
        "severity": "High",
        "description": "Northern leaf blight is caused by Exserohilum turcicum and produces large, cigar-shaped lesions on corn leaves.",
        "symptoms": [
            "Large, elliptical gray-green lesions 1-6 inches long",
            "Lesions turn tan with dark borders",
            "Starts on lower leaves, progresses upward",
            "Severely infected plants may have blighted appearance",
        ],
        "treatment": [
            "Apply foliar fungicides at VT/R1 growth stage",
            "Products with propiconazole or azoxystrobin are effective",
            "Economic threshold: 50% of plants infected below ear",
        ],
        "prevention": [
            "Use resistant hybrid varieties",
            "Rotate with non-corn crops for 1-2 years",
            "Tillage to bury infected residue",
            "Avoid overhead irrigation",
        ],
    },
    "Corn_(maize)___healthy": {
        "crop": "Corn (Maize)",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The corn plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular scouting", "Maintain fertility and moisture levels"],
    },
    "Grape___Black_rot": {
        "crop": "Grape",
        "disease": "Black Rot",
        "is_healthy": False,
        "severity": "High",
        "description": "Grape black rot, caused by Guignardia bidwellii, can destroy entire crops if uncontrolled.",
        "symptoms": [
            "Circular tan spots with dark borders on leaves",
            "Small black dots (pycnidia) within leaf lesions",
            "Berries shrivel and turn black (mummification)",
            "Shoot and tendril infections with dark lesions",
        ],
        "treatment": [
            "Apply mancozeb, myclobutanil, or captan fungicides",
            "Begin spray program at 1/2 inch shoot growth",
            "Spray every 10-14 days until veraison",
            "Remove mummified berries from vines",
        ],
        "prevention": [
            "Remove all mummified fruit and infected debris",
            "Prune to improve canopy air circulation",
            "Apply dormant copper sprays",
            "Scout regularly from budbreak",
        ],
    },
    "Grape___Esca_(Black_Measles)": {
        "crop": "Grape",
        "disease": "Esca (Black Measles)",
        "is_healthy": False,
        "severity": "High",
        "description": "Esca is a complex fungal disease affecting the wood and leaves of grapevines, caused by multiple fungal species.",
        "symptoms": [
            "Tiger-stripe pattern of yellow and green on leaves",
            "Margins of leaves dry and turn brown",
            "Dark spots on berries (measles symptom)",
            "Sudden vine collapse in acute form",
        ],
        "treatment": [
            "No curative chemical treatment available",
            "Prune out infected wood generously",
            "Protect pruning wounds with fungicide paste",
            "Remove and destroy severely infected vines",
        ],
        "prevention": [
            "Avoid pruning during wet weather",
            "Apply wound sealants after pruning",
            "Use disease-free planting material",
            "Delay pruning as late as possible",
        ],
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "crop": "Grape",
        "disease": "Leaf Blight (Isariopsis Leaf Spot)",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Caused by Pseudocercospora vitis, this disease causes leaf spots and premature defoliation.",
        "symptoms": [
            "Irregular dark brown spots on leaf surface",
            "Spots may have yellow halos",
            "Premature leaf drop reducing fruit quality",
            "Severe defoliation weakens vine",
        ],
        "treatment": [
            "Apply copper-based fungicides or mancozeb",
            "Treat at first symptom appearance",
            "Repeat at 10-14 day intervals in wet weather",
        ],
        "prevention": [
            "Improve canopy management for better air flow",
            "Remove infected leaves and debris",
            "Apply preventive copper sprays",
        ],
    },
    "Grape___healthy": {
        "crop": "Grape",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The grapevine appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular canopy management", "Annual dormant pruning"],
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "crop": "Orange",
        "disease": "Huanglongbing (Citrus Greening)",
        "is_healthy": False,
        "severity": "Critical",
        "description": "HLB is caused by Candidatus Liberibacter and is the most destructive citrus disease worldwide. There is currently no cure.",
        "symptoms": [
            "Asymmetrical yellowing (blotchy mottle) on leaves",
            "Small, lopsided fruit that remains green",
            "Bitter, unusable fruit",
            "Premature fruit drop",
            "Twig and branch dieback",
        ],
        "treatment": [
            "No curative treatment exists",
            "Remove and destroy infected trees to prevent spread",
            "Control Asian citrus psyllid (vector) with insecticides",
            "Thermotherapy in early stages (experimental)",
        ],
        "prevention": [
            "Use certified disease-free nursery stock",
            "Control Asian citrus psyllid populations",
            "Regular monitoring and early removal of infected trees",
            "Maintain tree health with proper nutrition",
        ],
    },
    "Peach___Bacterial_spot": {
        "crop": "Peach",
        "disease": "Bacterial Spot",
        "is_healthy": False,
        "severity": "High",
        "description": "Bacterial spot is caused by Xanthomonas arboricola pv. pruni and affects leaves, fruit, and shoots.",
        "symptoms": [
            "Small, water-soaked spots on leaves turning purple-brown",
            "Holes in leaves as infected tissue falls out (shothole effect)",
            "Sunken, dark spots on fruit surface",
            "Cracking of fruit lesions",
        ],
        "treatment": [
            "Apply copper-based bactericides during early season",
            "Oxytetracycline sprays during bloom period",
            "Avoid working in orchard when wet",
        ],
        "prevention": [
            "Plant resistant or tolerant peach varieties",
            "Avoid overhead irrigation",
            "Prune for good air circulation",
            "Apply copper during dormant season",
        ],
    },
    "Peach___healthy": {
        "crop": "Peach",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The peach tree appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular pruning", "Monitor for insect pests"],
    },
    "Pepper,_bell___Bacterial_spot": {
        "crop": "Bell Pepper",
        "disease": "Bacterial Spot",
        "is_healthy": False,
        "severity": "High",
        "description": "Bacterial spot of pepper is caused by Xanthomonas euvesicatoria and can cause severe defoliation and fruit loss.",
        "symptoms": [
            "Small, water-soaked spots on leaves and fruit",
            "Spots become brown with yellow halos",
            "Defoliation in severe infections",
            "Raised, scab-like lesions on fruit",
        ],
        "treatment": [
            "Apply copper hydroxide or copper sulfate sprays",
            "Combine copper with mancozeb for better control",
            "Remove heavily infected plants",
        ],
        "prevention": [
            "Use disease-free certified seed",
            "Hot water seed treatment at 50°C for 25 minutes",
            "Crop rotation with non-solanaceous crops",
            "Avoid overhead irrigation",
        ],
    },
    "Pepper,_bell___healthy": {
        "crop": "Bell Pepper",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The bell pepper plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Maintain consistent watering", "Scout for pests weekly"],
    },
    "Potato___Early_blight": {
        "crop": "Potato",
        "disease": "Early Blight",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Early blight is caused by Alternaria solani. It affects older leaves first and can significantly reduce yield.",
        "symptoms": [
            "Brown-black spots with concentric rings (target board pattern)",
            "Yellow halo surrounding lesions",
            "Lesions begin on older, lower leaves",
            "Severe defoliation reduces tuber yield",
        ],
        "treatment": [
            "Apply chlorothalonil, mancozeb, or azoxystrobin",
            "Begin sprays when symptoms first appear",
            "Spray every 7-10 days in wet conditions",
        ],
        "prevention": [
            "Use certified disease-free seed potatoes",
            "Crop rotation — avoid planting potatoes/tomatoes in same field",
            "Destroy volunteer potato plants",
            "Maintain plant vigor through balanced fertilization",
        ],
    },
    "Potato___Late_blight": {
        "crop": "Potato",
        "disease": "Late Blight",
        "is_healthy": False,
        "severity": "Critical",
        "description": "Late blight, caused by Phytophthora infestans, is the most devastating potato disease and caused the Irish Potato Famine.",
        "symptoms": [
            "Water-soaked, pale green lesions on leaf edges",
            "Lesions rapidly turn brown-black",
            "White mold on underside of leaves in humid conditions",
            "Potato tubers develop reddish-brown internal rot",
        ],
        "treatment": [
            "Apply metalaxyl or cymoxanil-based fungicides immediately",
            "Use mancozeb as protective spray",
            "Spray every 5-7 days in wet weather",
            "Destroy infected haulm before harvest",
        ],
        "prevention": [
            "Plant certified disease-free seed tubers",
            "Plant resistant varieties",
            "Hilling to protect tubers from spores",
            "Apply preventive copper sprays",
            "Monitor weather forecasts for blight risk periods",
        ],
    },
    "Potato___healthy": {
        "crop": "Potato",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The potato plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Maintain soil moisture", "Scout weekly for blight symptoms"],
    },
    "Raspberry___healthy": {
        "crop": "Raspberry",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The raspberry plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Annual cane removal after fruiting", "Maintain plant spacing"],
    },
    "Soybean___healthy": {
        "crop": "Soybean",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The soybean plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Crop rotation", "Weed control", "Monitor for aphids"],
    },
    "Squash___Powdery_mildew": {
        "crop": "Squash",
        "disease": "Powdery Mildew",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Powdery mildew on squash is caused by Podosphaera xanthii and thrives in warm, dry conditions.",
        "symptoms": [
            "White powdery spots on upper leaf surface",
            "Spots enlarge to cover entire leaf",
            "Yellowing and death of affected leaves",
            "Reduced fruit quality and quantity",
        ],
        "treatment": [
            "Apply potassium bicarbonate or sulfur fungicides",
            "Neem oil is an effective organic option",
            "Apply in early morning or evening to prevent burn",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Space plants for good air circulation",
            "Avoid overhead watering",
            "Remove infected leaves promptly",
        ],
    },
    "Strawberry___Leaf_scorch": {
        "crop": "Strawberry",
        "disease": "Leaf Scorch",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Leaf scorch is caused by Diplocarpon earlianum and produces purple-red spots on strawberry leaves.",
        "symptoms": [
            "Small purple-red spots on upper leaf surface",
            "Centers of spots turn gray-white",
            "Entire leaf may turn reddish-purple and die",
            "Weakened plants with reduced yield",
        ],
        "treatment": [
            "Apply myclobutanil or captan fungicides",
            "Remove and destroy infected leaves",
            "Renovate planting after harvest",
        ],
        "prevention": [
            "Use certified disease-free transplants",
            "Plant in well-drained soil",
            "Avoid overhead irrigation",
            "Renovate beds annually to reduce inoculum",
        ],
    },
    "Strawberry___healthy": {
        "crop": "Strawberry",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The strawberry plant appears healthy.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": ["Regular runner removal", "Annual bed renovation"],
    },
    "Tomato___Bacterial_spot": {
        "crop": "Tomato",
        "disease": "Bacterial Spot",
        "is_healthy": False,
        "severity": "High",
        "description": "Bacterial spot is caused by Xanthomonas species and is one of the most common tomato diseases.",
        "symptoms": [
            "Small, water-soaked spots on leaves turning brown",
            "Spots have yellow halos",
            "Raised, brown lesions on fruit",
            "Defoliation and sunscald of exposed fruit",
        ],
        "treatment": [
            "Apply copper-based bactericides weekly",
            "Combine with mancozeb for synergistic effect",
            "Remove heavily infected lower leaves",
        ],
        "prevention": [
            "Use disease-free certified seed",
            "Avoid overhead irrigation — use drip instead",
            "3-4 year crop rotation",
            "Stake plants for better air circulation",
        ],
    },
    "Tomato___Early_blight": {
        "crop": "Tomato",
        "disease": "Early Blight",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Early blight, caused by Alternaria solani, typically starts on older leaves and progresses upward.",
        "symptoms": [
            "Dark brown lesions with concentric rings (target pattern)",
            "Yellow area surrounding lesions",
            "Lower leaves affected first",
            "Fruit lesions near stem end",
        ],
        "treatment": [
            "Apply chlorothalonil or mancozeb fungicides",
            "Azoxystrobin provides both protective and curative action",
            "Spray every 7-10 days starting at first symptoms",
        ],
        "prevention": [
            "Mulch around plants to reduce soil splash",
            "Stake and prune for air circulation",
            "Crop rotation — do not plant tomatoes/potatoes in same spot",
            "Remove infected lower leaves",
        ],
    },
    "Tomato___Late_blight": {
        "crop": "Tomato",
        "disease": "Late Blight",
        "is_healthy": False,
        "severity": "Critical",
        "description": "Late blight (Phytophthora infestans) can destroy an entire tomato crop within days under favorable conditions.",
        "symptoms": [
            "Large, dark, water-soaked lesions on leaves",
            "White mold on underside of leaves",
            "Brown-black stems and petioles",
            "Firm, greasy-looking brown lesions on fruit",
        ],
        "treatment": [
            "Apply metalaxyl + mancozeb (Ridomil Gold) immediately",
            "Use cymoxanil or famoxadone-based products",
            "Spray every 5-7 days in wet conditions",
            "Remove and bag infected plant parts",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Avoid planting near potatoes",
            "Apply copper sprays preventively",
            "Monitor blight forecasting services",
        ],
    },
    "Tomato___Leaf_Mold": {
        "crop": "Tomato",
        "disease": "Leaf Mold",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Tomato leaf mold is caused by Passalora fulva and is most common in greenhouse tomatoes.",
        "symptoms": [
            "Pale greenish-yellow spots on upper leaf surface",
            "Olive-green to grayish-purple mold on lower surface",
            "Leaves curl, wither, and drop",
            "Reduced photosynthesis",
        ],
        "treatment": [
            "Apply chlorothalonil or mancozeb",
            "Improve ventilation in greenhouse",
            "Reduce humidity below 85%",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Maintain relative humidity below 85%",
            "Ensure good ventilation",
            "Avoid wetting leaves during irrigation",
        ],
    },
    "Tomato___Septoria_leaf_spot": {
        "crop": "Tomato",
        "disease": "Septoria Leaf Spot",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Septoria leaf spot, caused by Septoria lycopersici, is a very common and destructive disease.",
        "symptoms": [
            "Numerous small, circular spots with dark borders",
            "Tan-to-gray centers with dark specks (pycnidia)",
            "Starts on lower, older leaves",
            "Severe defoliation in wet seasons",
        ],
        "treatment": [
            "Apply chlorothalonil, mancozeb, or copper fungicides",
            "Begin when first symptoms appear",
            "Remove infected leaves below first fruit cluster",
        ],
        "prevention": [
            "Mulch to reduce soil splash",
            "Crop rotation 2-3 years",
            "Stake plants for air circulation",
            "Avoid working in wet garden",
        ],
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "crop": "Tomato",
        "disease": "Spider Mites (Two-Spotted)",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Two-spotted spider mites (Tetranychus urticae) are common pests that cause stippling damage to tomato leaves.",
        "symptoms": [
            "Fine stippling or bronzing on upper leaf surface",
            "Fine webbing on underside of leaves",
            "Leaves turn yellow and die",
            "Visible tiny mites on leaf underside",
        ],
        "treatment": [
            "Apply miticides (abamectin, bifenazate)",
            "Insecticidal soap or neem oil for organic control",
            "Strong water spray to dislodge mites",
            "Introduce predatory mites (Phytoseiulus persimilis)",
        ],
        "prevention": [
            "Maintain adequate soil moisture — dry conditions favor mites",
            "Avoid excessive nitrogen fertilization",
            "Monitor undersides of leaves regularly",
            "Avoid broad-spectrum pesticides that kill natural enemies",
        ],
    },
    "Tomato___Target_Spot": {
        "crop": "Tomato",
        "disease": "Target Spot",
        "is_healthy": False,
        "severity": "Medium",
        "description": "Target spot is caused by Corynespora cassiicola and produces distinctive concentric ring lesions.",
        "symptoms": [
            "Brown lesions with concentric rings on leaves",
            "Lesions coalesce in severe infections",
            "Brown, sunken lesions on fruit",
            "Defoliation reduces yield",
        ],
        "treatment": [
            "Apply azoxystrobin or chlorothalonil",
            "Difenoconazole-based fungicides are also effective",
        ],
        "prevention": [
            "Crop rotation",
            "Improve air circulation",
            "Remove crop debris after harvest",
        ],
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "crop": "Tomato",
        "disease": "Yellow Leaf Curl Virus (TYLCV)",
        "is_healthy": False,
        "severity": "Critical",
        "description": "TYLCV is transmitted by whiteflies (Bemisia tabaci) and is one of the most destructive tomato viruses globally.",
        "symptoms": [
            "Upward curling and yellowing of young leaves",
            "Small, crumpled leaves",
            "Stunted plant growth",
            "Severe reduction or complete loss of fruit",
        ],
        "treatment": [
            "No chemical cure for the virus",
            "Control whitefly vector with imidacloprid or thiamethoxam",
            "Remove and destroy infected plants immediately",
            "Use reflective mulches to deter whiteflies",
        ],
        "prevention": [
            "Plant TYLCV-resistant or tolerant varieties",
            "Use insect-proof nets in seedling stage",
            "Monitor and control whitefly populations",
            "Remove weed hosts of whiteflies",
        ],
    },
    "Tomato___Tomato_mosaic_virus": {
        "crop": "Tomato",
        "disease": "Tomato Mosaic Virus (ToMV)",
        "is_healthy": False,
        "severity": "High",
        "description": "Tomato mosaic virus is highly contagious and spreads through mechanical contact, infected tools, and seeds.",
        "symptoms": [
            "Light and dark green mosaic pattern on leaves",
            "Leaf distortion and malformation",
            "Stunted plant growth",
            "Reduced fruit quality with internal browning",
        ],
        "treatment": [
            "No chemical cure",
            "Remove and destroy infected plants",
            "Disinfect tools with 10% bleach solution",
            "Wash hands thoroughly before handling plants",
        ],
        "prevention": [
            "Use virus-free certified seed",
            "Seed treatment with trisodium phosphate",
            "Do not use tobacco products near tomatoes",
            "Disinfect all tools between plants",
        ],
    },
    "Tomato___healthy": {
        "crop": "Tomato",
        "disease": "Healthy",
        "is_healthy": True,
        "severity": "None",
        "description": "The tomato plant appears healthy with no visible disease symptoms.",
        "symptoms": [],
        "treatment": ["No treatment required"],
        "prevention": [
            "Continue regular monitoring every 3-4 days",
            "Maintain consistent watering schedule",
            "Apply balanced fertilizer as needed",
            "Scout for early pest and disease signs",
        ],
    },
}

CLASS_NAMES = sorted(DISEASE_DB.keys())


def get_disease_info(class_name: str) -> dict:
    """Return disease info for a given class name."""
    return DISEASE_DB.get(class_name, {
        "crop": "Unknown",
        "disease": "Unknown",
        "is_healthy": False,
        "severity": "Unknown",
        "description": "No information available for this class.",
        "symptoms": [],
        "treatment": ["Consult a local agricultural expert."],
        "prevention": [],
    })
